[package]
name = "make-a-lisp-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cli"
src = "src/bin/cli.rs"

[lib]

[dependencies]
color-eyre = "0.6.3"
rustyline = "14.0.0"
thiserror = "1.0.63"
